-- UPDATE users set user_role = 'admin' where email = 'ianmachariak17@gmail.com';

-- EXECUTE usp_CreateUser 'dfb54dfd25f45dfsv45sdv4sd5vsd54', 'Ian Macharia', 'ianmachariak17@gmail.com', 'karianmash', '123';
-- Create user
-- CREATE PROCEDURE usp_CreateUser
--     (
--     @user_id VARCHAR(100),
--     @fullname VARCHAR (55),
--     @email VARCHAR (50),
--     @username VARCHAR(20),
--     @hashed_password VARCHAR(100)
-- )
-- AS
-- BEGIN
--     INSERT INTO users
--         (
--         user_id,
--         fullname,
--         email,
--         username,
--         hashed_password
--         )
--     VALUES
--         (
--             @user_id,
--             @fullname,
--             @email,
--             @username,
--             @hashed_password
--     );
-- END;

-- EXECUTE usp_GetUser 'ianmachariak17@gmail.com';
-- Procedure to get user when logging in
-- CREATE PROCEDURE usp_GetUser(@email VARCHAR(50))
-- AS
-- BEGIN
--     SELECT * FROM users WHERE email = @email;
-- END

-- Procedure to get all users
-- CREATE PROCEDURE usp_GetUsers
-- AS
-- BEGIN
--     SELECT * FROM users WHERE user_role = 'user';
-- END




-- Create/update a parcel
-- CREATE PROCEDURE usp_CreateUpdateParcel
--     (
--     @parcel_id VARCHAR(100),
--     @track_id VARCHAR (50),
--     @shipper VARCHAR (50),
--     @weight VARCHAR (10),
--     @status VARCHAR(20),
--     @sender VARCHAR(100),
--     @receiver VARCHAR (55),
--     @item_name VARCHAR (50),
--     @price VARCHAR (50),
--     @origin_location VARCHAR(20),
--     @pick_up_location VARCHAR(100),
--     @in_progress_email VARCHAR (10),
--     @completed_email VARCHAR (10),
--     @canceled_email VARCHAR (10),
--     @user_id VARCHAR(100)
-- )
-- AS
-- BEGIN
--     IF EXISTS (SELECT 1
--     FROM parcels
--     WHERE parcel_id = @parcel_id)

--     BEGIN
--         UPDATE parcels SET
--             parcel_id = @parcel_id,
--             track_id = @track_id,
--             shipper = @shipper,
--             weight = @weight,
--             status = @status,
--             sender = @sender,
--             receiver = @receiver,
--             item_name = @item_name,
--             price = @price,
--             origin_location = @origin_location,
--             pick_up_location = @pick_up_location,
--             in_progress_email = @in_progress_email,
--             completed_email = @completed_email,
--             canceled_email = @canceled_email,
--             user_id = @user_id
--         WHERE parcel_id = @parcel_id
--         PRINT 'Parcel updated successfully...'
--     END

--     ELSE 
--         BEGIN
--         INSERT INTO parcels
--             (
--             parcel_id,
--             track_id,
--             shipper,
--             weight,
--             status,
--             sender,
--             receiver,
--             item_name,
--             price,
--             origin_location,
--             pick_up_location,
--             in_progress_email,
--             completed_email,
--             canceled_email,
--             user_id
--             )
--         VALUES
--             (
--                 @parcel_id,
--                 @track_id,
--                 @shipper,
--                 @weight,
--                 @status,
--                 @sender,
--                 @receiver,
--                 @item_name,
--                 @price,
--                 @origin_location,
--                 @pick_up_location,
--                 @in_progress_email,
--                 @completed_email,
--                 @canceled_email,
--                 @user_id
--             )
--         PRINT 'Parcel created successfully...'
--     END
-- END;


-- Procedure to get all users parcels
-- CREATE PROCEDURE usp_GetUserParcels (
--     @user_id VARCHAR(100)
-- )
-- AS
-- BEGIN
--     SELECT * FROM parcels WHERE user_id = @user_id;
-- END

-- Procedure to get all parcels
-- CREATE PROCEDURE usp_GetParcels 
-- AS
-- BEGIN
--     SELECT * FROM parcels WHERE is_deleted = 'False';
-- END

-- Procedure to get single parcel
-- CREATE PROCEDURE usp_GetParcel (
--     @parcel_id VARCHAR(100)
-- )
-- AS
-- BEGIN
--     SELECT * FROM parcels WHERE parcel_id = @parcel_id;
-- END

-- Procedure to delete a parcel
-- CREATE PROCEDURE usp_DeleteParcel (
--     @parcel_id VARCHAR(100)
-- )
-- AS
-- BEGIN
--     UPDATE parcels SET is_deleted = 'True' WHERE parcel_id = @parcel_id;
-- END